name: changelog

on:
    pull_request:
        types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
    check_changelog:
        name: Changelog Entry Check

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Grep CHANGES.md for PR number
              if: contains(github.event.pull_request.labels.*.name, 'skip news') != true # skip 'skip news' labelled PRs
              run: |
                  grep -Pz "\((\n\s*)?#${{ github.event.pull_request.number }}(\n\s*)?\)" HISTORY.rst || \
                  (echo "Please add '(#${{ github.event.pull_request.number }})' change line to HISTORY.rst" && \
                  exit 1)

